version: '3.9'
services:
  backend:
    container_name: backend-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always